log: info

# === PROMETHEUS ===
# prometheus configuration
# ==================
prometheus:
    enabled: false
    port: 2112

# === POOLS ===
# An array that defines what pools should be crawled and how they are served.
# - chainid: is the chain id of the pool, e.g. kyve-1, koan-1, korellia-2
# - poolid: respective poolId
# - indexer: defines what indexer to use, the indexer also defines how to access the data
#            e.g. EthBlobs will provide following URLs: "/beacon/blob_sidecars?block_height={block_height}", "/beacon/blob_sidecars?slot_number={slot_number}"
# - slug: what slug should be used when serving the pools. The slug is a unique prefix for each pool when requesting its data.
#         e.g. with the slug 'ethereum' and the indexer EthBlobs the resulting url will be: "/ethereum/beacon/blob_sidecars?..."
# =============
crawler:
  threads: 4
pools:
  - chainid: kaon-1
    indexer: EthBlobs
    poolid: 21
    slug: ethereum
    bundleStartId: 0
  - chainid: korellia-2
    indexer: Celestia
    poolid: 111
    slug: celestia
    bundleStartId: 0
  - chainid: kyve-1
    indexer: Tendermint
    poolid: 1
    slug: osmosis
    excludeProof: true

# === DATABASE ===
# database configuration
# ================
database:
  # supported databases: sqlite (default), postgres
  type: postgres
  # the database name, if you use sqlite this will the the database file. default: ./database.db
  dbname: ""
  # following attributes are only relevant when using postgres, you don't need them for sqlite
  host: "REDACTED"
  # IMPORTANT: this is postgres database port, not the port the app will use to serve
  port: 5432
  user: "REDACTED"
  password: "REDACTED"

# === SERVER ===
# server configuration. The server will use the pools config to know what pools to serve
# ==============
server:
  # port of the server
  port: 80

# === STORAGE ===
# storage configuration.
# ===============
storage:
  # the type of storage to use. available options: local (default), s3
  type: s3
  # only relevant when using local storage, can be left empty when using AWS
  path: ../data
  threads: 94
  # what compression to use when storing/uploading the data
  # available options: gzip (default), none
  compression: gzip

  # S3 CONFIG
  # The following configs are only relevant when using S3

  # your R2 or AWS endpoint
  aws-endpoint: "REDACTED"
  # your bucket name
  bucketname: "REDACTED"
  # CDN where to fetch the data
  cdn: "REDACTED"
  # your access key id and your access key secret
  credentials:
    keyid: "REDACTED"
    keysecret: "REDACTED"
  # what region to use for the aws config. default: auto
  region: auto

# === ENDPOINTS ===
# specify custom endpoints & fallback
# endpoints for each storage provider and chain
# if you dont provide any endpoints, official endpoints will be set as default
# =================
endpoints:
  storage:
    1:
      - https://arweave.net
      # define as many fallback endpoints as you want
      # - https://arweave.net
    2:
      - https://arweave.net
    3:
      - https://storage.kyve.network
  chains:
    kaon-1:
      - https://api.kaon.kyve.network
      # same here, define your fallback endpoints
      # - https://api.kaon.kyve.network
    korellia-2:
      - https://api.korellia.kyve.network
    kyve-1:
      - https://api.kyve.network
