# log level values: info, warning, debug, error, none
log: info

# === POOLS ===
# An array that defines what pools should be crawled and how they are served.
# - chainid: is the chain id of the pool, e. g. kyve-1, koan-1, korellia-2
# - poolid: respective poolId
# - indexer: defines what indexer to use, the indexer also defines how to access the data
#            e. g. EthBlobs will provide following URLs: "/beacon/blob_sidecars?block_height={block_height}", "/beacon/blob_sidecars?slot_number={slot_number}"
# - slug: what slug should be used when serving the pools. The slug is a unique prefix for each pool when requesting its data.
#         e. g. with the slug 'ethereum' and the indexer EthBlobs the resulting url will be: "/ethereum/beacon/blob_sidecars?..."
# - bundleStartId: Bundle-ID of the first bundle that should be indexed (Default: 0 -> means all bundles will be indexed).
# =============
pools:
    - chainid: kaon-1
      indexer: EthBlobs
      poolid: 21
      slug: ethereum
      bundleStartId: 0
      proofAttached: true
    - chainid: korellia-2
      indexer: Tendermint
      poolid: 113
      slug: injective
      bundleStartId: 141
      proofAttached: true

# === DATABASE ===
# database configuration
# ================
database:
    # supported databases: sqlite (default), postgres
    type: sqlite 
    # the database name, if you use sqlite this will the the database file. default: ./database.db
    dbname: indexer.db 
    # following attributes are only relevant when using postgres, you don't need them for sqlite
    host: "localhost"
    # IMPORTANT: this is postgres database port, not the port the app will use to serve
    port: 5432 
    user: "admin"
    password: "root"

# === SERVER ===
# server configuration. The server will use the pools config to know what pools to serve
# ==============
server: 
    # port of the server
    port: 4242 

# === SERVER ===
# crawler configuration. Only relevant when running the crawling process
# ==============
crawler:
    # how many threads are used for downloading & processing the bundles
    threads: 4

# === STORAGE ===
# storage configuration.
# ===============
storage:
    # the type of storage to use. available options: local (default), s3
    type: local
    # how many threads are used to save/upload the processed bundle. Default 8
    threads: 8
    # only relevant when using local storage, can be left empty when using AWS
    path: ./data 
    # what compression to use when storing/uploading the data
    # available options: gzip (default), none
    compression: gzip
    
    # S3 CONFIG
    # The following configs are only relevant when using S3

    # your R2 or AWS endpoint
    aws-endpoint: "http://example-bucket.s3-website.us-west-2.amazonaws.com/" 
    # your bucket name
    bucketname: "example-bucket" 
    # CDN where to fetch the data
    cdn: "https://example.domain/" 
    # your access key id and your acces key secret
    credentials:
        keyid: "<access_key_id>" 
        keysecret: "<access_key_secret>"
    # what region to use for the aws config. default: auto
    region: auto 

# === ENDPOINTS ===
# specify custom endpoints & fallback
# endpoints for each storage provider and chain
# if you dont provide any endpoints, official endpoints will be set as default
# =================
endpoints:
    storage:
        1:
            - https://arweave.net
            # define as many fallback endpoints as you want
            # - https://arweave.net
        2:
            - https://arweave.net
        3:
            - https://storage.kyve.network
    chains:
        kaon-1:
            - https://api.kaon.kyve.network
            # same here, define your fallback endpoints
            # - https://api.kaon.kyve.network
        korellia-2:
            - https://api.korellia.kyve.network
        kyve-1:
            - https://api.kyve.network
